[package]
name = "git-credential-github-app-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [[bin]]
# name = "git-credential-github-app"
# path = "src/bin/helper.rs"

# [[bin]]
# name = "git-credential-github-app-daemon"
# path = "src/bin/daemon.rs"

[dependencies]
futures-util = "0.3.25"
jsonwebtoken = "8.2.0"
octocrab = "0.18.1"
secrecy = "0.8.0"
tokio = { version = "1.24.2", features = ["rt-multi-thread", "io-std", "macros"] }
tokio-util = { version = "0.7.4", features = ["codec"] }
